monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - bus # Events are logged in the dedicated "event" channel when it exists
when@dev:
    monolog:
        handlers:
            messenger_all:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.messenger.log"
                level: debug
                channels: ["messenger"]
                max_files: 10
            
            # only WARNING and above
            messenger_warning_plus:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.messenger-warning+.log"
                level: warning
                channels: ["messenger"]
                max_files: 5
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!bus", "!messenger"]    
            bus:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.bus.log"
                level: debug
                channels: ["bus"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!bus", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!bus"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            messenger_all:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.messenger.log"
                level: debug
                channels: ["messenger"]
                max_files: 10
            
            # only WARNING and above
            messenger_warning_plus:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.messenger-warning+.log"
                level: warning
                channels: ["messenger"]
                max_files: 5
            tmp:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!bus", "!messenger"]
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!bus", "!doctrine", "!messenger"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
